# This is a basic workflow to help you get started with Actions

name: CI
env:
  NODE_OPTIONS: "--max_old_space_size=4096 --openssl-legacy-provider"

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v4
        with:
          node-version: "18.19.1"
      - run: tsc --version
      - run: npm install -g yarn@^1.19.0 && yarn install

      - name: Check formatting with prettier
        run: yarn prettier-check

      - name: Build TerriaJS tests
        run: yarn gulp lint release --continue
        env:
          NODE_OPTIONS: "--max_old_space_size=4096 --openssl-legacy-provider"

      - name: Run tests using xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn gulp test-firefox
